export { default as HomeLanding } from "./LandingPage";
export { default as GoalInfo } from "./GoalInfo";
export { default as ProductList } from "./ProductList";
export { default as Features } from "./Features";
export { default as Blogs } from "./Blogs";
export { default as CareerBox } from "./CareerBox";
export { default as Clients } from "./Clients";
export { default as Testimonials } from "./Testimonials";
export { default as Subscribe } from "./Subscribe";
